.PHONY: test serve fmt check fixtures

PORT ?= 8080

test:
	node --test 'test/**/*.test.js'

serve:
	node tools/serve.js $(PORT)

fmt:
	@echo "no formatter configured yet"

check: test

# Fixtures generated by HackTV (https://codeberg.org/fsphil/hacktv).
# 10 frames of 75% colour bars at 4×Fsc as int16 baseband; ~14 MB.
# Long enough to exercise vsync re-acquisition and start-offset
# scrubbing in the demo. Requires `hacktv` on PATH; `apt install hacktv`
# on Debian / Ubuntu.
fixtures: fixtures/hacktv-bars.int16

fixtures/hacktv-bars.int16:
	@mkdir -p fixtures
	hacktv -m pal -s 17734475 --noaudio -o file:- -t int16 test:colourbars \
	  | head -c 14200000 > $@
	@ls -lh $@
